### ISSUE TITLE
Próba połączenia - wystąpił błąd o treści:

### ISSUE THREAD

**Issue by xylorin** [MK-PL/AllegroRSS#10]

**Comment by xylorin** [comment]
1. Próba połączenia
Wystąpił błąd o treści:
Error: .wait() for .main-content timed out after 10000msec
    at newDone (C:\Users\Kuba\Desktop\RSS\node_modules\nightmare\lib\actions.js:545:9)
    at Timeout._onTimeout (C:\Users\Kuba\Desktop\RSS\node_modules\nightmare\lib\actions.js:578:5)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

Sprawdzone na kilku komputerach - nie działa od wczoraj (11.04)

**Comment by sirozhkas** [comment]
Witam.
Potwierdzam, mam ten sam problem. Nie można także stworzyć nowego kanału RSS, jest ten sam błąd.

**Comment by kl0007** [comment]
To samo u mnie - również instalacja na Windowsie (7).

**Comment by MK-PL** [comment]
@xylorin @sirozhkas @kl0007 Dziękuje za Wasze zgłoszenia, wrzuciłem poprawkę. Sprawdźcie i dajcie znać, czy działa. Pozdrawiam!

**Comment by sirozhkas** [comment]
@MK-PL, działa, ale często pojawia się inny błąd:

`1. Proba polaczenia
Wystapil blad o tresci:
{ TypeError: Cannot read property 'seller' of undefined
    at fn (<anonymous>:18:122)
    at javascript (<anonymous>:68:21)
    at <anonymous>:83:3
    at EventEmitter.electron.ipcRenderer.on (C:\Program Files\nodejs\node_module
s\npm\node_modules\AllegroRSS-master\node_modules\electron\dist\resources\electr
on.asar\renderer\init.js:63:28)
    at emitMany (events.js:146:13)
    at EventEmitter.emit (events.js:223:7) code: -1 }
-----------
2. Proba polaczenia
Wystapil blad o tresci:
{ TypeError: Cannot read property 'seller' of undefined
    at fn (<anonymous>:18:122)
    at javascript (<anonymous>:68:21)
    at <anonymous>:83:3
    at EventEmitter.electron.ipcRenderer.on (C:\Program Files\nodejs\node_module
s\npm\node_modules\AllegroRSS-master\node_modules\electron\dist\resources\electr
on.asar\renderer\init.js:63:28)
    at emitMany (events.js:146:13)
    at EventEmitter.emit (events.js:223:7) code: -1 }
-----------
3. Proba polaczenia
Wystapil blad o tresci:
{ TypeError: Cannot read property 'seller' of undefined
    at fn (<anonymous>:18:122)
    at javascript (<anonymous>:68:21)
    at <anonymous>:83:3
    at EventEmitter.electron.ipcRenderer.on (C:\Program Files\nodejs\node_module
s\npm\node_modules\AllegroRSS-master\node_modules\electron\dist\resources\electr
on.asar\renderer\init.js:63:28)
    at emitMany (events.js:146:13)
    at EventEmitter.emit (events.js:223:7) code: -1 }
-----------`

**Comment by fakk3** [comment]
Mam ten sam błąd po zainstalowaniu najnowszej wersji skryptu. Na starej wszystko działało normalnie.

**Comment by MK-PL** [comment]
@sirozhkas @fakk3 Wrzuciłem poprawkę przed chwilą. Wywaliłem na razie informację o sprzedawcy, bo zaimplementowanie tego wymaga dodatkowych warunków i stąd były te błędy.

**Comment by sirozhkas** [comment]
@MK-PL teraz działa :) 
Dziękuję!

**Comment by xylorin** [comment]
Po ściągnięciu nowej wersji problem rozwiązany. Dzięki!
