### ISSUE TITLE
Znowu nie działa :<

### ISSUE THREAD

**Issue by JuniorJPDJ** [MK-PL/AllegroRSS#19]
Wszystko jest w logach ;)
```
allegrorss_1  | 2019-11-13T15:27:23.269220496Z Uruchomiono serwer na porcie 80
allegrorss_1  | 2019-11-13T15:28:08.495205326Z -----------
allegrorss_1  | 2019-11-13T15:28:08.495378678Z GENEROWANIE RSS - start dla adresu URL: https://allegro.pl/kategoria/podzespoly-komputerowe-zasilacze-259437?price_to=100&stan=nowe&stan=używane&stan=po zwrocie&stan=powystawowe&moc-zasilacza-od=500&order=n&price_from=20
allegrorss_1  | 2019-11-13T15:28:08.495411910Z 1. Próba połączenia
allegrorss_1  | 2019-11-13T15:28:08.497482404Z Wed, 13 Nov 2019 15:28:08 GMT nightmare queuing process start
allegrorss_1  | 2019-11-13T15:28:08.497807126Z Wed, 13 Nov 2019 15:28:08 GMT nightmare queueing action "goto" for about:blank
allegrorss_1  | 2019-11-13T15:28:08.497902598Z Wed, 13 Nov 2019 15:28:08 GMT nightmare queueing action "cookies"
allegrorss_1  | 2019-11-13T15:28:08.498277415Z Wed, 13 Nov 2019 15:28:08 GMT nightmare running
allegrorss_1  | 2019-11-13T15:28:10.185648376Z Wed, 13 Nov 2019 15:28:10 GMT nightmare queueing action "goto" for https://allegro.pl/kategoria/podzespoly-komputerowe-zasilacze-259437?price_to=100&stan=nowe&stan=używane&stan=po zwrocie&stan=powystawowe&moc-zasilacza-od=500&order=n&price_from=20
allegrorss_1  | 2019-11-13T15:28:10.185688784Z Wed, 13 Nov 2019 15:28:10 GMT nightmare queueing action "title"
allegrorss_1  | 2019-11-13T15:28:10.185696645Z Wed, 13 Nov 2019 15:28:10 GMT nightmare running
allegrorss_1  | 2019-11-13T15:28:12.720722579Z Wed, 13 Nov 2019 15:28:12 GMT nightmare queueing action "click"
allegrorss_1  | 2019-11-13T15:28:12.720771608Z Wed, 13 Nov 2019 15:28:12 GMT nightmare queueing action "scrollTo"
allegrorss_1  | 2019-11-13T15:28:12.720838421Z Wed, 13 Nov 2019 15:28:12 GMT nightmare queueing action "wait"
allegrorss_1  | 2019-11-13T15:28:12.720937238Z Wed, 13 Nov 2019 15:28:12 GMT nightmare queueing action "exists"
allegrorss_1  | 2019-11-13T15:28:12.720983293Z Wed, 13 Nov 2019 15:28:12 GMT nightmare running
allegrorss_1  | 2019-11-13T15:28:12.736993386Z Wed, 13 Nov 2019 15:28:12 GMT nightmare running
allegrorss_1  | 2019-11-13T15:28:12.738571957Z Wystąpił błąd o treści:
allegrorss_1  | 2019-11-13T15:28:12.741441842Z Error: Unable to find element by selector: button[data-analytics-interaction-value="accept"]
allegrorss_1  | 2019-11-13T15:28:12.741536185Z     at fn (<anonymous>:9:15)
allegrorss_1  | 2019-11-13T15:28:12.741571294Z     at javascript (<anonymous>:34:21)
allegrorss_1  | 2019-11-13T15:28:12.741592535Z     at <anonymous>:49:3
allegrorss_1  | 2019-11-13T15:28:12.741599195Z     at EventEmitter.electron.ipcRenderer.on (/workspace/node_modules/electron/dist/resources/electron.asar/renderer/web-frame-init.js:36:30)
allegrorss_1  | 2019-11-13T15:28:12.741604631Z     at emitMany (events.js:147:13)
allegrorss_1  | 2019-11-13T15:28:12.741617367Z     at EventEmitter.emit (events.js:224:7) {
allegrorss_1  | 2019-11-13T15:28:12.741759532Z   code: -1
allegrorss_1  | 2019-11-13T15:28:12.741774072Z }
allegrorss_1  | 2019-11-13T15:28:12.741782466Z -----------
allegrorss_1  | 2019-11-13T15:28:12.741788212Z 2. Próba połączenia
allegrorss_1  | 2019-11-13T15:28:12.741953152Z Wed, 13 Nov 2019 15:28:12 GMT nightmare queuing process start
allegrorss_1  | 2019-11-13T15:28:12.742090253Z Wed, 13 Nov 2019 15:28:12 GMT nightmare queueing action "goto" for about:blank
allegrorss_1  | 2019-11-13T15:28:12.742340671Z Wed, 13 Nov 2019 15:28:12 GMT nightmare queueing action "cookies"
allegrorss_1  | 2019-11-13T15:28:12.742358949Z Wed, 13 Nov 2019 15:28:12 GMT nightmare running
allegrorss_1  | 2019-11-13T15:28:12.828351658Z Wed, 13 Nov 2019 15:28:12 GMT nightmare electron child process exited with code 0: success!
allegrorss_1  | 2019-11-13T15:28:13.241715365Z Wed, 13 Nov 2019 15:28:13 GMT nightmare queueing action "goto" for https://allegro.pl/kategoria/podzespoly-komputerowe-zasilacze-259437?price_to=100&stan=nowe&stan=używane&stan=po zwrocie&stan=powystawowe&moc-zasilacza-od=500&order=n&price_from=20
allegrorss_1  | 2019-11-13T15:28:13.241860295Z Wed, 13 Nov 2019 15:28:13 GMT nightmare queueing action "title"
allegrorss_1  | 2019-11-13T15:28:13.242044804Z Wed, 13 Nov 2019 15:28:13 GMT nightmare running
allegrorss_1  | 2019-11-13T15:28:15.994454386Z Wed, 13 Nov 2019 15:28:15 GMT nightmare queueing action "click"
allegrorss_1  | 2019-11-13T15:28:15.994718488Z Wed, 13 Nov 2019 15:28:15 GMT nightmare queueing action "scrollTo"
allegrorss_1  | 2019-11-13T15:28:15.994739718Z Wed, 13 Nov 2019 15:28:15 GMT nightmare queueing action "wait"
allegrorss_1  | 2019-11-13T15:28:15.994750610Z Wed, 13 Nov 2019 15:28:15 GMT nightmare queueing action "exists"
allegrorss_1  | 2019-11-13T15:28:15.994756348Z Wed, 13 Nov 2019 15:28:15 GMT nightmare running
allegrorss_1  | 2019-11-13T15:28:16.002441763Z Wed, 13 Nov 2019 15:28:16 GMT nightmare running
allegrorss_1  | 2019-11-13T15:28:16.002692243Z Wystąpił błąd o treści:
allegrorss_1  | 2019-11-13T15:28:16.002899507Z Error: Unable to find element by selector: button[data-analytics-interaction-value="accept"]
allegrorss_1  | 2019-11-13T15:28:16.002931410Z     at fn (<anonymous>:9:15)
allegrorss_1  | 2019-11-13T15:28:16.002943316Z     at javascript (<anonymous>:34:21)
allegrorss_1  | 2019-11-13T15:28:16.002950001Z     at <anonymous>:49:3
allegrorss_1  | 2019-11-13T15:28:16.002955574Z     at EventEmitter.electron.ipcRenderer.on (/workspace/node_modules/electron/dist/resources/electron.asar/renderer/web-frame-init.js:36:30)
allegrorss_1  | 2019-11-13T15:28:16.002961689Z     at emitMany (events.js:147:13)
allegrorss_1  | 2019-11-13T15:28:16.002966522Z     at EventEmitter.emit (events.js:224:7) {
allegrorss_1  | 2019-11-13T15:28:16.002976243Z   code: -1
allegrorss_1  | 2019-11-13T15:28:16.002983729Z }
allegrorss_1  | 2019-11-13T15:28:16.002990240Z -----------
allegrorss_1  | 2019-11-13T15:28:16.002996254Z 3. Próba połączenia
allegrorss_1  | 2019-11-13T15:28:16.003263234Z Wed, 13 Nov 2019 15:28:16 GMT nightmare queuing process start
allegrorss_1  | 2019-11-13T15:28:16.003367911Z Wed, 13 Nov 2019 15:28:16 GMT nightmare queueing action "goto" for about:blank
allegrorss_1  | 2019-11-13T15:28:16.003441139Z Wed, 13 Nov 2019 15:28:16 GMT nightmare queueing action "cookies"
allegrorss_1  | 2019-11-13T15:28:16.003603062Z Wed, 13 Nov 2019 15:28:16 GMT nightmare running
allegrorss_1  | 2019-11-13T15:28:16.042025514Z Wed, 13 Nov 2019 15:28:16 GMT nightmare electron child process exited with code 0: success!
allegrorss_1  | 2019-11-13T15:28:16.576978946Z Wed, 13 Nov 2019 15:28:16 GMT nightmare queueing action "goto" for https://allegro.pl/kategoria/podzespoly-komputerowe-zasilacze-259437?price_to=100&stan=nowe&stan=używane&stan=po zwrocie&stan=powystawowe&moc-zasilacza-od=500&order=n&price_from=20
allegrorss_1  | 2019-11-13T15:28:16.577032596Z Wed, 13 Nov 2019 15:28:16 GMT nightmare queueing action "title"
allegrorss_1  | 2019-11-13T15:28:16.577040181Z Wed, 13 Nov 2019 15:28:16 GMT nightmare running
allegrorss_1  | 2019-11-13T15:28:22.974778232Z Wed, 13 Nov 2019 15:28:22 GMT nightmare queueing action "click"
allegrorss_1  | 2019-11-13T15:28:22.974827896Z Wed, 13 Nov 2019 15:28:22 GMT nightmare queueing action "scrollTo"
allegrorss_1  | 2019-11-13T15:28:22.974853534Z Wed, 13 Nov 2019 15:28:22 GMT nightmare queueing action "wait"
allegrorss_1  | 2019-11-13T15:28:22.974900418Z Wed, 13 Nov 2019 15:28:22 GMT nightmare queueing action "exists"
allegrorss_1  | 2019-11-13T15:28:22.974939842Z Wed, 13 Nov 2019 15:28:22 GMT nightmare running
allegrorss_1  | 2019-11-13T15:28:22.977022418Z Wed, 13 Nov 2019 15:28:22 GMT nightmare running
allegrorss_1  | 2019-11-13T15:28:22.977288209Z Wystąpił błąd o treści:
allegrorss_1  | 2019-11-13T15:28:22.977488813Z Error: Unable to find element by selector: button[data-analytics-interaction-value="accept"]
allegrorss_1  | 2019-11-13T15:28:22.977511943Z     at fn (<anonymous>:9:15)
allegrorss_1  | 2019-11-13T15:28:22.977518208Z     at javascript (<anonymous>:34:21)
allegrorss_1  | 2019-11-13T15:28:22.977521366Z     at <anonymous>:49:3
allegrorss_1  | 2019-11-13T15:28:22.977525813Z     at EventEmitter.electron.ipcRenderer.on (/workspace/node_modules/electron/dist/resources/electron.asar/renderer/web-frame-init.js:36:30)
allegrorss_1  | 2019-11-13T15:28:22.977529155Z     at emitMany (events.js:147:13)
allegrorss_1  | 2019-11-13T15:28:22.977532088Z     at EventEmitter.emit (events.js:224:7) {
allegrorss_1  | 2019-11-13T15:28:22.977535072Z   code: -1
allegrorss_1  | 2019-11-13T15:28:22.977538387Z }
allegrorss_1  | 2019-11-13T15:28:22.977543277Z -----------
allegrorss_1  | 2019-11-13T15:28:22.977595299Z Przerwano generowanie RSS, ponieważ nie można odczytać podanego adresu URL: https://allegro.pl/kategoria/podzespoly-komputerowe-zasilacze-259437?price_to=100&stan=nowe&stan=używane&stan=po zwrocie&stan=powystawowe&moc-zasilacza-od=500&order=n&price_from=20
allegrorss_1  | 2019-11-13T15:28:23.019371927Z Wed, 13 Nov 2019 15:28:23 GMT nightmare electron child process exited with code 0: success!
```

**Comment by MK-PL** [comment]
Dziękuję za zgłoszenie, błąd został poprawiony: https://github.com/MK-PL/AllegroRSS/commit/85998baed8d0adb477fb54e5f182f0944925de78
