### ISSUE TITLE
Błąd przy próbie połączenia

### ISSUE THREAD

**Issue by ddand** [MK-PL/AllegroRSS#27]
Cześć, od jakiegoś czasu skrypt nie działa - przy próbie połączenia "Wystąpił błąd o treści:
{ Error: Unable to find element by selector: button[data-role="accept-consent"]
    at fn (<anonymous>:9:15)
    at javascript (<anonymous>:34:21)
    at <anonymous>:49:3
    at EventEmitter.electron.ipcRenderer.on (c:\Program Files\nodejs\node_modules\npm\node_modules\AllegroRSS-master\node_modules\electron\dist\resources\electron.asar\renderer\web-frame-init.js:36:30)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7) code: -1 }
    
Czy jest szansa na poprawkę w nieodległej przyszłości? :)

**Comment by Aurosonic** [comment]
Cześć, z mojej strony również pytanie/prośba, czy szykuje się może jakaś poprawka do skryptu przywracająca działanie ? :)
